spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Eternalblue123
    url: jdbc:mysql://localhost:3306/sc
mybatis-plus:
  type-aliases-package: com.eterblue
  global-config:
    db-config:
      id-type: auto
      update-strategy: not_null
      logic-not-delete-value: 1
      logic-delete-field: status
      logic-delete-value: 0
  mapper-locations: "classpath*:/mapper/**/*.xml"
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
logging:
  level:
    com:
      eterblue: debug
server:
  port: 8080