spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Eternalblue123
    url: jdbc:mysql://localhost:3306/sc
  redis:
    port: 6379
    host: localhost
    database: 2
    auth: Eternalblue123
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 10MB
mybatis-plus:
  type-aliases-package: com.eterblue.model
  global-config:
    db-config:
      id-type: auto
      update-strategy: not_null
#      logic-not-delete-value: 1
#      logic-delete-field: status
#      logic-delete-value: 0
  mapper-locations: "classpath*:/mapper/**/*.xml"
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
logging:
  level:
    com:
      eterblue:
        mapper: debug
        service: info
        controller: info
server:
  port: 8080
